name: CI

on:
  pull_request:
  push:
    branches:
      - master
      - next
      - rc
  workflow_dispatch:

jobs:
  test:
    name: Test
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: '20'

      - run: |
          npm clean-install
          npm run test:ci

      - name: Coveralls
        uses: coverallsapp/github-action@v2
